import 'package:airlink/models/registers_model.dart';
import 'package:get/get.dart';

class SearchListController extends GetxController {
  final searchResult = [].obs;
  final searchList = [
    SearchRegisterData(
        name: 'Device Type', startIndex: 2, length: 0, type: 'r', value: ''),
    SearchRegisterData(
        name: 'ODU Hardware Version',
        startIndex: 3,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'ODU Firmware Version',
        startIndex: 4,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Compressor Type',
        startIndex: 7,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Configration Flags',
        startIndex: 8,
        length: 0,
        type: 'r/w',
        value: ''),
    // SearchRegisterData(
    // name: 'saveSettings', startIndex: 9, length: 0, type: 'r/w', value: ''),
    SearchRegisterData(
        name: 'Commanded Operation Mode',
        startIndex: 10,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Commanded Compressor Speed',
        startIndex: 11,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Operation Mode',
        startIndex: 12,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Compressor Speed',
        startIndex: 13,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Status Flags', startIndex: 14, length: 0, type: 'r', value: ''),
    SearchRegisterData(
        name: 'Error Code', startIndex: 15, length: 0, type: 'r', value: ''),
    SearchRegisterData(
        name: 'Indoor Fan Speed',
        startIndex: 16,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Fan RPM',
        startIndex: 17,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Coil Temperature',
        startIndex: 18,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Error Code',
        startIndex: 19,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'ODU Ambient Temperature',
        startIndex: 20,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'ODU Coi Temperature',
        startIndex: 21,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Discharge Line Temperature',
        startIndex: 24,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Suction Line Temperature',
        startIndex: 25,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'HP Saturation Temperature',
        startIndex: 26,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'LP Saturation Temperature',
        startIndex: 27,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Hp Pressure', startIndex: 28, length: 0, type: 'r', value: ''),
    SearchRegisterData(
        name: 'Lp Pressure', startIndex: 29, length: 0, type: 'r', value: ''),
    SearchRegisterData(
        name: '10V Input', startIndex: 30, length: 0, type: 'r', value: ''),
    SearchRegisterData(
        name: '10V Output', startIndex: 31, length: 0, type: 'r/w', value: ''),
    SearchRegisterData(
        name: 'Relay Outputs',
        startIndex: 32,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'External Inputs',
        startIndex: 33,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'EXV Pulses Target',
        startIndex: 34,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'EXV Pulses Actual',
        startIndex: 35,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'ODU State', startIndex: 36, length: 0, type: 'r', value: ''),
    SearchRegisterData(
        name: 'ODU State Time',
        startIndex: 37,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'IDU Commanded Compressor Speed',
        startIndex: 38,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Error Flags', startIndex: 39, length: 0, type: 'r', value: ''),
    SearchRegisterData(
        name: 'Other Flags', startIndex: 40, length: 0, type: 'r', value: ''),
    SearchRegisterData(
        name: 'Oil Loss Time', startIndex: 41, length: 0, type: 'r', value: ''),
    SearchRegisterData(
        name: 'Oil Return Speed',
        startIndex: 42,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Defrost Confirm Time',
        startIndex: 43,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Defrost Hold Time',
        startIndex: 44,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Operating Envelope',
        startIndex: 45,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Discharge Superheat',
        startIndex: 46,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Superheat', startIndex: 47, length: 0, type: 'r', value: ''),
    SearchRegisterData(
        name: 'Superheat Target',
        startIndex: 48,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Superheat Control Divider',
        startIndex: 49,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Superheat Trip Count',
        startIndex: 50,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Error Log 1', startIndex: 51, length: 0, type: 'r', value: ''),
    SearchRegisterData(
        name: 'Error Log 2', startIndex: 52, length: 0, type: 'r', value: ''),
    SearchRegisterData(
        name: 'Error Log 3', startIndex: 53, length: 0, type: 'r', value: ''),
    SearchRegisterData(
        name: 'Error Log 4', startIndex: 54, length: 0, type: 'r', value: ''),
    SearchRegisterData(
        name: 'Error Log 5', startIndex: 55, length: 0, type: 'r', value: ''),
    SearchRegisterData(
        name: 'IDU Good Packets',
        startIndex: 56,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'IDU Bad Packets',
        startIndex: 57,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Oil Return Duration',
        startIndex: 59,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'VSD Compressor Speed',
        startIndex: 60,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'VSD Compressor Torque',
        startIndex: 61,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'VSD AC Input Voltage',
        startIndex: 65,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'VSD AC Input Current',
        startIndex: 66,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'VSD AC Input Power',
        startIndex: 67,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'VSD Motor Phase',
        startIndex: 68,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'VSD Inverter Temprature',
        startIndex: 70,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'VSD Motor Temprature',
        startIndex: 76,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'BMS Operation Mode',
        startIndex: 90,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'BMS Indoor Fan Speed',
        startIndex: 91,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'BMS Set Temperature',
        startIndex: 92,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'BMS Room Temperature',
        startIndex: 93,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'BMS ADV Compressor Speed',
        startIndex: 95,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'BMS Zones', startIndex: 97, length: 0, type: 'r/w', value: ''),
    SearchRegisterData(
        name: 'Indoor Fan Low Speed',
        startIndex: 100,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Fan Medium Speed',
        startIndex: 101,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Fan High Speed',
        startIndex: 102,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Fan Low Speed RPM Limit',
        startIndex: 103,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Fan Medium Speed RPM Limit',
        startIndex: 104,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Fan High Speed RPM Limit',
        startIndex: 105,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Fan Defrost Speed',
        startIndex: 106,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Fan Idle Speed',
        startIndex: 107,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Fan Filter Hours Countdown',
        startIndex: 108,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Fan Filter Hours Reset',
        startIndex: 109,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Damper Output',
        startIndex: 110,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Proportional Band',
        startIndex: 112,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Integral Divider',
        startIndex: 113,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Firmware',
        startIndex: 115,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Temperature S1',
        startIndex: 119,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Temperature S2',
        startIndex: 120,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Temperature S3',
        startIndex: 121,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Controller Temperature C1',
        startIndex: 122,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Controller Temperature C2',
        startIndex: 123,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Controller Temperature C3',
        startIndex: 124,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Temperature 1',
        startIndex: 125,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Temperature 2',
        startIndex: 126,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Temperature 3',
        startIndex: 127,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Temperature 4',
        startIndex: 128,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Temperature 5',
        startIndex: 129,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Temperature 6',
        startIndex: 130,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Temperature 7',
        startIndex: 131,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Temperature 8',
        startIndex: 132,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Temperature 9',
        startIndex: 133,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Temperature 10',
        startIndex: 134,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Temperature 11',
        startIndex: 135,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Temperature 12',
        startIndex: 136,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Temperature 13',
        startIndex: 137,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Temperature 14',
        startIndex: 138,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Temperature 15',
        startIndex: 139,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Temperature 16',
        startIndex: 140,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Controller Humidity C1',
        startIndex: 141,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Controller Humidity C2',
        startIndex: 142,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Controller Humidity C3',
        startIndex: 143,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Humidity 1',
        startIndex: 144,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Humidity 2',
        startIndex: 145,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Humidity 3',
        startIndex: 146,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Humidity 4',
        startIndex: 147,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Humidity 5',
        startIndex: 148,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Humidity 6',
        startIndex: 149,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Humidity 7',
        startIndex: 150,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Humidity 8',
        startIndex: 151,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Humidity 9',
        startIndex: 152,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Humidity 10',
        startIndex: 153,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Humidity 11',
        startIndex: 154,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Humidity 12',
        startIndex: 155,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Humidity 13',
        startIndex: 156,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Humidity 14',
        startIndex: 157,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Humidity 15',
        startIndex: 158,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Remote Humidity 16',
        startIndex: 159,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Controller Weighting Offset C1',
        startIndex: 177,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Controller Weighting Offset C2',
        startIndex: 178,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Controller Weighting Offset C3',
        startIndex: 179,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Sensor Weighting Offset S1',
        startIndex: 180,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Sensor Weighting Offset S2',
        startIndex: 181,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Sensor Weighting Offset S3',
        startIndex: 182,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Weighting Offset 1',
        startIndex: 183,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Weighting Offset 2',
        startIndex: 184,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Weighting Offset 3',
        startIndex: 185,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Weighting Offset 4',
        startIndex: 186,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Weighting Offset 5',
        startIndex: 187,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Weighting Offset 6',
        startIndex: 188,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Weighting Offset 7',
        startIndex: 189,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Weighting Offset 8',
        startIndex: 190,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Weighting Offset 9',
        startIndex: 191,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Weighting Offset 10',
        startIndex: 192,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Weighting Offset 11',
        startIndex: 193,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Weighting Offset 12',
        startIndex: 194,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Weighting Offset 13',
        startIndex: 195,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Weighting Offset 14',
        startIndex: 196,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Weighting Offset 15',
        startIndex: 197,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Weighting Offset 16',
        startIndex: 198,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Config 1',
        startIndex: 199,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Config 2',
        startIndex: 200,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Config 3',
        startIndex: 201,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Config 4',
        startIndex: 202,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Config 5',
        startIndex: 203,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Config 6',
        startIndex: 204,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Config 7',
        startIndex: 205,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Config 8',
        startIndex: 206,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Config 9',
        startIndex: 207,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Config 10',
        startIndex: 208,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Config 11',
        startIndex: 209,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Config 12',
        startIndex: 210,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Config 13',
        startIndex: 211,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Config 14',
        startIndex: 212,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Config 15',
        startIndex: 213,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Remote Config 16',
        startIndex: 214,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Zone Detection Status',
        startIndex: 250,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Zone Detection Flags',
        startIndex: 251,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Zone Enabled', startIndex: 252, length: 0, type: 'r', value: ''),
    SearchRegisterData(
        name: 'Last Zone Protection',
        startIndex: 253,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Actual Temperature Zone 1',
        startIndex: 254,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Actual Temperature Zone 2',
        startIndex: 255,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Actual Temperature Zone 3',
        startIndex: 256,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Actual Temperature Zone 4',
        startIndex: 257,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Actual Temperature Zone 5',
        startIndex: 258,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Actual Temperature Zone 6',
        startIndex: 259,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Actual Temperature Zone 7',
        startIndex: 260,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Actual Temperature Zone 8',
        startIndex: 261,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Actual Humidity Zone 1',
        startIndex: 262,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Actual Humidity Zone 2',
        startIndex: 263,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Actual Humidity Zone 3',
        startIndex: 264,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Actual Humidity Zone 4',
        startIndex: 265,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Actual Humidity Zone 5',
        startIndex: 266,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Actual Humidity Zone 6',
        startIndex: 267,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Actual Humidity Zone 7',
        startIndex: 268,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Actual Humidity Zone 8',
        startIndex: 269,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Zone Damper Position 1',
        startIndex: 279,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Zone Damper Position 2',
        startIndex: 280,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Zone Damper Position 3',
        startIndex: 281,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Zone Damper Position 4',
        startIndex: 282,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Zone Damper Position 5',
        startIndex: 283,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Zone Damper Position 6',
        startIndex: 284,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Zone Damper Position 7',
        startIndex: 285,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Zone Damper Position 8',
        startIndex: 286,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Economiser Mode',
        startIndex: 450,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Econ Outside Min Temperature',
        startIndex: 451,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Econ Outside Max Temperature',
        startIndex: 452,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Econ Outside Min Humidity',
        startIndex: 453,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Econ Outside Max Humidity',
        startIndex: 454,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Econ Outside Max Moisture',
        startIndex: 455,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Econ Outside Max Dew Point',
        startIndex: 456,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Econ Outside Enthalpy',
        startIndex: 457,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Econ Enthalpy Deltq',
        startIndex: 458,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Econ Co2 Low Threshold',
        startIndex: 459,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Econ Co2 High Threshold',
        startIndex: 460,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Econ Co2 Damper Low Position',
        startIndex: 461,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'Econ Co2 Damper High Threshold',
        startIndex: 462,
        length: 0,
        type: 'r/w',
        value: ''),
    SearchRegisterData(
        name: 'ODU Fan Speed',
        startIndex: 500,
        length: 0,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Serial',
        startIndex: 1000,
        length: 3,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'Indoor Model',
        startIndex: 1003,
        length: 7,
        type: 'r',
        value: ''),
    SearchRegisterData(
        name: 'ODU Serial', startIndex: 1010, length: 3, type: 'r', value: ''),
    SearchRegisterData(
        name: 'ODU Model', startIndex: 1013, length: 7, type: 'r', value: ''),
  ].obs;
}
